theme: minima
minima:
  skin: dark
title: Salience AI
url: "https://salienceai.co"
repoBaseUrl: https://github.com/salienceai/salience-website
plugins:
  - jekyll-sitemap
tagline: Programmable AI
description: AI startup providing programmable AI agents.
twitter:
  username: salience_ai
  card: summary
social:
  name: Salience AI
  links:
    - https://x.com/salience_ai
    - https://github.com/salience-ai

# Social media usernames for Minima footer
twitter_username: salience_ai
github_username: salience-ai

# Default image for social sharing
image:
  path: /assets/image/salience-ai-icon.png
  alt: Salience AI company logo

# Configure pages collection
collections:
  pages:
    output: true
    permalink: /:name

